site_name: Illumine
site_url: https://benfreking123.github.io/IllumineWeb
repo_url: https://github.com/benfreking123/IllumineWeb

# Turn OFF strict so warnings don't fail your build
strict: false

# MkDocs will read markdown from the folder we checkout your vault into
docs_dir: vault

theme:
  name: material

plugins:
  - search
  # Keep roamlinks to support [[WikiLinks]]. If you don't need it, remove it.
  - roamlinks

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
