site_name: Illumine
site_url: https://benfreking123.github.io/IllumineWeb
repo_url: https://github.com/benfreking123/IllumineWeb
strict: false
docs_dir: vault

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy

nav:
  - Home: index.md
  - Essays: Essays/
  - Practice:
    - Practice/Pathway.md
  - Experiments: Experiments/

plugins:
  - search:
      separator: '[\s\-]+'
  - roamlinks
  - exclude:
      glob:
        - ".obsidian/**"
        - "Templates/**"
        - "Unorganized/**"
        - "Private/**"
        - "Drafts/**"
        - "README.md"
        - "test.md"
  # - mermaid2   # optional; enable + pip install if you want diagrams

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: material/github
      link: https://github.com/benfreking123
    - icon: material/email
      link: mailto:benjamin.freking@gmail.com
  generator: false

extra_css:
  - assets/extra.css
