site_name: Illumine
site_url: https://benfreking123.github.io/IllumineWeb
repo_url: https://github.com/benfreking123/IllumineWeb

strict: false
docs_dir: vault

theme:
  name: material

plugins:
  - search
  - roamlinks
  - exclude:
      glob:
        # Hide these files/folders from the site build entirely
        - ".obsidian/**"
        - "Templates/**"
        - "Unorganized/**"
        - "Private/**"
        - "Drafts/**"
        - "README.md"
        - "test.md"

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
